### ISSUE TITLE
[FATAL] uncaughtException: RSV1 must be clear

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk#254]
2018-06-05T12:24:55.181Z - error: uncaughtException: RSV1 must be clear date=Tue Jun 05 2018 15:24:55 GMT+0300 (MSK), pid=18447, uid=0, gid=0, cwd=/var/www/hawk.so/hawk, execPath=/usr/bin/node, version=v9.11.1, argv=[/usr/bin/node, /var/www/hawk.so/hawk/bin/www], rss=143556608, heapTotal=44396544, heapUsed=34766168, external=18271220, loadavg=[0.14404296875, 0.23095703125, 0.26953125], uptime=686680
Error: RSV1 must be clear
    at Receiver.getInfo (/var/www/hawk.so/hawk/node_modules/ws/lib/Receiver.js:191:18)
    at Receiver.startLoop (/var/www/hawk.so/hawk/node_modules/ws/lib/Receiver.js:153:16)
    at Receiver.add (/var/www/hawk.so/hawk/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/var/www/hawk.so/hawk/node_modules/ws/lib/WebSocket.js:142:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)

**Comment by talyguryn** [comment]
2018-06-08T14:10:11.923Z - error: uncaughtException: RSV1 must be clear date=Fri Jun 08 2018 17:10:11 GMT+0300 (MSK), pid=2466, uid=0, gid=0, cwd=/var/www/hawk.so/hawk, execPath=/usr/bin/node, version=v9.11.1, argv=[/usr/bin/node, /var/www/hawk.so/hawk/bin/www], rss=177270784, heapTotal=52006912, heapUsed=36467736, external=18232285, loadavg=[0.1083984375, 0.158203125, 0.20166015625], uptime=952197
Error: RSV1 must be clear
    at Receiver.getInfo (/var/www/hawk.so/hawk/node_modules/ws/lib/Receiver.js:191:18)
    at Receiver.startLoop (/var/www/hawk.so/hawk/node_modules/ws/lib/Receiver.js:153:16)
    at Receiver.add (/var/www/hawk.so/hawk/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/var/www/hawk.so/hawk/node_modules/ws/lib/WebSocket.js:142:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
